### PR TITLE
Allow for additional components (JREs) in the cache

### PR DESCRIPTION
**Pull request by ghaug**
As described in this [issue](https://github.com/cloudfoundry/java-buildpack/issues/848) we are using the offline package of the Java Buildpack and have the problem that we need to bundle more than one JRE with it. We can't uncomment more than one JRE in the components.yml file and a download on deployment is not possible (disabled and no network anyway). We have a little hack in place that additionally bundles SapMachine JRE so our customers can select it if they wish. However, we would prefer a more elegant solution.

I've made a tiny change that reads ADD_TO_CACHE during the bundling process and adds components to the offline cache that are not specified in components.yml

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
This looks good to me. Thanks for doing it. @maintainers: Is there any chance to get this merged?

**Comment by ekcasey** [comment]
Hey @ghaug thanks for the contribution and apologies for the slow response.

A couple things:

1. This now fails if you don't specify `ADD_TO_CACHE`:
```
bundle exec rake clean package OFFLINE=true PINNED=true
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/Users/ekcasey/workspace/cloudfoundry/java-buildpack/rakelib/dependency_cache_task.rb:113:in `component_ids'
/Users/ekcasey/workspace/cloudfoundry/java-buildpack/rakelib/dependency_cache_task.rb:45:in `initialize'
/Users/ekcasey/workspace/cloudfoundry/java-buildpack/Rakefile:42:in `new'
/Users/ekcasey/workspace/cloudfoundry/java-buildpack/Rakefile:42:in `<top (required)>'
/Users/ekcasey/.rbenv/versions/2.5.8/bin/bundle:23:in `load'
/Users/ekcasey/.rbenv/versions/2.5.8/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

2. After Digging into this more, I suspect the feature we are trying to enable already works, if you uncomment multiple JREs in [`components.yml`](https://github.com/cloudfoundry/java-buildpack/blob/f888b34fbe93671ea74c003bea91cda8bd4bb21a/config/components.yml#L31). The [first JRE will be the default](https://github.com/cloudfoundry/java-buildpack/blob/main/lib/java_buildpack/buildpack.rb#L67-L71) and others can be set with `JBP_CONFIG_COMPONENTS`. Maybe we should just document the existing behavior instead of adding the `ADD_TO_CACHE` env var?

**Comment by ghaug** [comment]
Hey @ekcasey thanks for looking into this.

re your comments:

1. Sorry for the stupid mistake, I'll fix that.
2. Has this feature been recently introduced? When I tried it didn't work like that.

**Comment by ghaug** [comment]
I've updated the PR to fix the bug @ekcasey mentioned as 1.

**Review by ekcasey — APPROVED** [review]

**Pull request merged**
