### PR TITLE
Add Riverbed Appinternals Support

### PR DESCRIPTION
**Pull request by fwanggg**
**Riverbed’s SteelCentral AppInternals software is hereby expressly designated as “NOT A CONTRIBUTION”, notwithstanding the fact that Riverbed may provide a URL or other references in its Contributions that direct the user to a copy of SteelCentral AppInternals software.  Riverbed’s provision of such URL or references will not constitute a Contribution of the SteelCentral AppInternals software.** 

Hi Guys,
I once opened a pull request without legal's approval, https://github.com/cloudfoundry/java-buildpack/pull/553 
now that legal has approved and CLA has been signed and sent to  contributors@cloudfoundry.org, i am opening a new one.
The nature of  the agent is still the same. It's an APM agent just like appdyanamics or dynatrace that captures transactions of java application.

Here are some differences  in terms of status of our PCF support
1. we now have a place to host our agent zip file, and is specified  in the riverbed_appinternals_agent.yml
2. we are now officially on PivNet and that's where our pivotal file located https://network.pivotal.io/products/riverbed-appinternals/.  JBP alone won't work, You'll need to install the tile in a PCF cluster(assuming you guys have plenty of those), if you have to test our software as a whole. 

two questions: 

Last time i was told to get a Riverbed Appinternals SaaS account for Cloud Foundry maintainer to test the JBP. Is that still a requirement? When would you actually use that?

Is user generally recommended to use the greatest and latest from master(the default behavior) or they'd better choose a specific release version? How would a JBP user choose what version of JBP to use? How often do you guys release a new version?

thanks in advance

### CODE REVIEW

**Comment by fwanggg** [comment]
Can someone comment on when this pr can be reviewed?

**Comment by nebhale** [comment]
> Last time i was told to get a Riverbed Appinternals SaaS account for Cloud Foundry maintainer to test the JBP. Is that still a requirement? When would you actually use that?

We'd need it at the very least to validate that this integration works before merging it in.  We'd also want the account available to us if we ever need to diagnose problems with the integration.  Finally, at some point shortly in the future, we'd add a full-scale automated test that ensured that integration worked automatically.

> Is user generally recommended to use the greatest and latest from master(the default behavior) or they'd better choose a specific release version? How would a JBP user choose what version of JBP to use? How often do you guys release a new version?

Most users do not use buildpack out of `master` (although it is generally stable enough to do so).  Instead, users generally rely on [releases](https://github.com/cloudfoundry/java-buildpack/releases).  The last couple of months not-withstanding we have averaged about three weeks between releases over the last five years.

**Comment by fwanggg** [comment]
@nebhale i'll make the changes. 
Could you please give me a pointer to the doc on how to choose to use a specific release of JBP, with and without internet connection?
Do you have access to any PCF clusters that you can install our pivotal file? Without that, you won't see any data flow to our saas server.

**Comment by nebhale** [comment]
> Could you please give me a pointer to the doc on how to choose to use a specific release of JBP, with and without internet connection?

Cloud Foundry documentation for buildpacks can be found [here](https://docs.cloudfoundry.org/adminguide/buildpacks.html).  You need to get a buildpack artifact (online artifacts can be found attached to GitHub releases, offline artifacts are distributed by vendors like Pivotal) and update an existing or create a new buildpack.  For online buildpacks, `cf push` will also let you [specify a buildpack](https://cli.cloudfoundry.org/en-US/cf/push.html) including the branch or tag you'd like to use.

> Do you have access to any PCF clusters that you can install our pivotal file? Without that, you won't see any data flow to our saas server.

Yes.

**Comment by fwanggg** [comment]
@nebhale cool. i've edited my comment to include another question but you probably didn't notice. the question is:
"Our SAAS version now supports free trial, it's a very easy signup process. you can use it for 14 days free and monitor up to 10 JVMs. Would that suffice for testing purpose?"

**Comment by nebhale** [comment]
That will suffice for this initial contribution, but longer term we need a permanent account in order to ensure that the integration is healthy as part of routine automated testing.

**Comment by nebhale** [comment]
@fwanggg I'm currently getting the following failures.  Can you please run the tests again and see if you are as well?

```plain
Failures:

  1) JavaBuildpack::Framework::RiverbedAppinternalsAgent  supports riverbed-appinternals-agent service
     Failure/Error: expect(component.supports?).to be true
     
       expected true
            got false
     # ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:45:in `block (3 levels) in <top (required)>'

  2) JavaBuildpack::Framework::RiverbedAppinternalsAgent  detects with riverbed-appinternals-agent service
     Failure/Error: expect(component.detect).to eq("riverbed-appinternals-agent=#{version}")
     
       expected: "riverbed-appinternals-agent=0.0.0"
            got: nil
     
       (compared using ==)
     # ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:49:in `block (3 levels) in <top (required)>'

  3) JavaBuildpack::Framework::RiverbedAppinternalsAgent   unzip riverbed appinternals agent zip file
     Failure/Error: print "#{'----->'.red.bold} Downloading #{name.blue.bold} #{version.to_s.blue} from #{uri.sanitize_uri} "
     
     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:92:in `download'
     # ./lib/java_buildpack/component/base_component.rb:151:in `download_zip'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:92:in `download_zip'
     # ./lib/java_buildpack/framework/riverbed_appinternals_agent.rb:65:in `compile'
     # ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:55:in `block (4 levels) in <top (required)>'

Finished in 16.52 seconds (files took 0.73519 seconds to load)
872 examples, 3 failures

Failed examples:

rspec ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:44 # JavaBuildpack::Framework::RiverbedAppinternalsAgent  supports riverbed-appinternals-agent service
rspec ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:48 # JavaBuildpack::Framework::RiverbedAppinternalsAgent  detects with riverbed-appinternals-agent service
rspec ./spec/java_buildpack/framework/riverbed_appinternals_agent_spec.rb:52 # JavaBuildpack::Framework::RiverbedAppinternalsAgent   unzip riverbed appinternals agent zip file
```

**Comment by fwanggg** [comment]
@nebhale 
No i don't see those errors when testing locally on ubuntu os. It looks like "supports" returns false and causing the following test failures. Are you running those tests on Linux? I made sure those tests only pass on Linux because that's the only platform we intend to support at the moment?

Besides that: 
i ran "bundle exec rake". All the errors i can see are below:
`Failed examples:

rspec ./spec/bin/detect_spec.rb:24 # detect script returns zero if success
rspec ./spec/bin/detect_spec.rb:40 # detect script truncates long detect strings
rspec ./spec/bin/compile_spec.rb:26 # compile script returns zero if success
rspec ./spec/bin/compile_spec.rb:33 # compile script fails to compile when no containers detect
rspec ./spec/bin/release_spec.rb:24 # release script returns zero if success
rspec ./spec/bin/release_spec.rb:30 # release script fails to release when no containers detect
`
None of them seems to be related to my changes. And i ran tests again cloudfoundry/master, i get the same errors. So i assume you guys are aware of these.

**Comment by nebhale** [comment]
Yep, that’ll be exactly what it is.  The code does need to pass in macOS, so I’ll add some protection around it to ensure a green run.

The failures you’re seeing are not expected, but since they are “real” integration tests that properly go to the internet to download dependencies, etc. are almost certainly related to a corporate proxy in your network path.  You can set proxy parameters if you’d like to see them pass, but given that your code isn’t breaking anything new in my testing, you probably don’t need to.  I’ll try to get this in today.

**Comment by fwanggg** [comment]
@nebhale cool. i am fine with the test results given what you said.  before you mentioned bundle exec rake, I actually imported the prj to rubyMine and ran the "fake" integration tests(using the fake artifacts) in there and i saw all tests passing as well.
Let me know how you want to proceed with end to end test later
1)try everything yourself(by reading https://docs.pivotal.io/partners/riverbed-appinternals/index.html) or 2)I give you some quick instructions through comment or slack

**Pull request closed without merging**
