### PR TITLE
Check for Roles when retrieving operator credentials

### PR DESCRIPTION
**Pull request by rebeccachin**
[#151847755]

Signed-off-by: Rebecca Chin <rchin@pivotal.io>

### CODE REVIEW

**Comment by nebhale** [comment]
@rebeccachin Can you please provide more detail about exactly what is going on with this PR?  As the commit message does not describe what the change was and why the change was made, I'm not sure if this was accidentally submitted to the project or if you expect it to be incorporated.

**Comment by ekcasey** [comment]
We rebased this. This PR provides forwards compatibility with new pcc credentials format that will be landing in pcc v1.3.0.

**Comment by ekcasey** [comment]
Any updates on this?

**Comment by ekcasey** [comment]
awesome thanks!

**Pull request closed without merging**
