### PR TITLE
Upgrading gemfire version to 8.2

### PR DESCRIPTION
**Pull request by sbawaska**
Upgraded to latest GemFire release to be used for session caching.

### CODE REVIEW

**Comment by cgfrost** [comment]
Hi,

Thanks for the contribution, can you sign the CLA and I will merge it in. It looks like you work for Pivotal though so if you are in any of the Pivotal Orgs you should just be able to make your membership public and be approved automatically.

**Comment by sbawaska** [comment]
I have made my "pivotal-cf" membership public.

**Comment by nebhale** [comment]
@cgfrost Should we actually slacken this restriction to `8.+`?  It seems like you've uploaded a couple of subsequent releases that we not actually picked up by users.

**Comment by sbawaska** [comment]
The problem with that is if the build-pack picks up a GemFire release, before the service team. Since GemFire servers are backwards compatible, an old client in the buildpack will be able to talk to a new server, but if the buildpack picks up a new client, it won't be able to talk to an old server.

**Comment by nebhale** [comment]
But that's true now as we upgrade to 8.2 as well.  There's no way to guarantee that any user will have upgraded when the buildpack does.  Until the client is backwards compatible, there's no real way to solve this problem.  In lieu of a solution, we go for consistency which is latest possible version at all times.

**Pull request closed without merging**
