### PR TITLE
Appdynamic 2.4

### PR DESCRIPTION
**Pull request by hhercules**
What these changes make available for us is the ability to have a top level environment name where we can then group applications, or have a top level application with environment information to separate out apps with same name but different environment. Also this helps us remove AppDynamics license overuse by creating reusable instance names. Also this allows us to view history since name stays consistent.

### CODE REVIEW

**Comment by nebhale** [comment]
@hhercules Thank you for the submissions, but we probably won't be accepting either this PR or #155.  Rather than having any fundamental issue with them, they overlap some already scheduled work that we're doing.

First, we're going to be [making `applicationName`, `tierName`, and `nodeName` configurable](https://www.pivotaltracker.com/story/show/89413382) using a precedence system involving the service credentials payload and configuration files.  Secondly, we're going to be making [all configuration available via environment variables](https://github.com/cloudfoundry/java-buildpack/issues/122).

Between these two issues, I believe that we'll add the configurability that you require.  Would you agree?

**Comment by hhercules** [comment]
Yes that will be great, thank you.

Hercules, Christian Hildebrando

**Comment by cgfrost** [comment]
As there have been no more comments for a while, this request is being closed off.

**Comment by nebhale** [comment]
The first bit of this has now gone in: https://github.com/cloudfoundry/java-buildpack/pull/164

**Comment by nebhale** [comment]
The second bit of this has now gone in: https://github.com/cloudfoundry/java-buildpack/issues/122

**Pull request closed without merging**
