### PR TITLE
Add sensible defaults for Tomcat http connector

### PR DESCRIPTION
**Pull request by lhotari**
- change connectionTimeout to 5000 ms (Tomcat default is 60000ms)
- enable SO_REUSEADDR and TCP_NODELAY by default
- limit maxThreads to 50 (Tomcat default is 200)

### CODE REVIEW

**Comment by nebhale** [comment]
@lhotari Have you run these changes past @markt-asf?  I'm not confident in making the change for everyone unless he's on board.

**Comment by markt-asf** [comment]
connectionTimeout="5000"
This also reduces the keep-alive timeout since none is explicitly set. Are you sure that is what you want? Also, 5000 is on the low side for the connection/read time out. It would be fine on a LAN. For mobile clients with a poor connection it could be a little low.

socket.soReuseAddress="true"
What problem are you trying to solve with this setting?

socket.tcpNoDelay="true"
This should be OK but I'd be interested to know if there was any measureable improvement when using this option.

maxThreads="50"
If anything, I'd say 200 was too low a default for production usage. What is the reasoning for lowering to 50?

minSpareThreads="10"
This is already the default so why specify it?

**Comment by lhotari** [comment]
@markt-asf Some context: In the CloudFoundry Warden container, the Java process gets killed without warning when the RSS goes over the limit for the container. The number of active threads is one factor in how much memory the Java process will consume. I started another issue about taking the maximum number in to account when calculating the memory sizes in Java buildpack: #157. That is related to this Tomcat configuration PR. 

`maxThreads="50"`
Each thread will consume more memory. Going to 200 threads will kill the container when there isn't enough memory allocated for 200 threads. Perhaps 50 is a more sensible default for Tomcat in CloudFoundry since we should be allocating memory for the threads too when doing the memory calculation (#157). 
`minSpareThreads="10"`
I just added this to show what the minimum number of threads is.

`connectionTimeout="5000"`
I noticed that the default out-of-box Tomcat config sets `connectionTimeout="20000"` in the server.xml file . I found out that the default is 60000 when you don't specify connectionTImeout. That is certainly too high. Perhaps 5000 is too low, but I found many suggesting that value for webservers. You are right that it might cause problems for mobile clients. 

`socket.soReuseAddress="true"`
We don't need this one.

**Comment by nebhale** [comment]
@lhotari If the number of threads in contributing to an OOM then the solution is not to modify the number of threads, but rather modify the memory allocations to take into account their _actual_ proportion of the memory space.  It seems that if we do that, the only thing left in play on this issue is `connectionTimeout`.

**Comment by markt-asf** [comment]
OK, with no connectionTimeout specified it will default to 60000 (60s) and I agree that is too high. Absent an argument for a different value I'd recommend explicitly setting it to 20000 (20s) to align with Tomcat's out of the box value.

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/91083074

**Comment by cgfrost** [comment]
Closing without pulling. A smaller change has been made to set the `connectionTimeout` to 20s. After all the discussion this option best suits all of the buildpack users. If there is a special use case that requires different configuration the existing strategy of forking the buildpack should be used.

Commit: 50d9b5f88ccb064aed38641811255c1c8a7e1d0a

**Pull request closed without merging**
