### PR TITLE
Update version of agents to be consistent with the latest releases

### PR DESCRIPTION
**Pull request by DMevada**
Before this commit, the current version of agents to be downloaded was 10.+. After this commit, the version will be 11.+.

### CODE REVIEW

**Comment by DMevada** [comment]
Hi @nebhale 

Any updates on this PR?

-Dhruv

**Comment by DMevada** [comment]
Hi Ben,

I have added the latest version of our agent that supports 11.+ to our index file.

-Dhruv

**Comment by nebhale** [comment]
Great.  Can you please make it `https://` as well?  By policy we no longer include dependencies acquired via HTTP.

**Comment by DMevada** [comment]
Hi Ben,

The config.yml file already has our repo location as https. 
The repo itself is also https already as we cannot host our binaries without that.

-Dhruv

**Comment by nebhale** [comment]
The binary in question (`11.1.1_0`) has an `http://` URI:

```
➜  ~ curl https://ca.bintray.com/apm-agents/index.yml
---
11.1.1_0: http://ca.bintray.com/apm-agents/agent-default-11.1.1_0.tar
10.7.0_412: https://ca.bintray.com/apm-agents/agent-noinstaller-default-unix-10.6.0.179.tar
10.7.0_116: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.7.0_116default.unix.tar
10.7.0_70: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.7.0_70default.unix.tar
10.6.0_113: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_113default.unix.tar
10.6.0_0: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.6.0_0default.unix.tar
10.5.2_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.2_15default.unix.tar
10.5.1_6: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.1_6default.unix.tar
10.5.0_20: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.5.0_20default.unix.tar
10.3.0_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.3.0_15default.unix.tar
10.2.0_27: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.2.0_27default.unix.tar
10.1.0_15: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.1.0_15default.unix.tar
10.0.0_16: https://ca.bintray.com/apm-agents/IntroscopeAgentFiles-NoInstaller10.0.0_16default.unix.tar
```

**Pull request closed without merging**
