### PR TITLE
Update JAVA_OPTS documentation

### PR DESCRIPTION
**Pull request by youngm**
A stab at updating some JAVA_OPTS documentation for JBP4.

### CODE REVIEW

**Comment by nebhale** [comment]
Looks great.  What do you think about removing `-Xmx` specifically.  I cannot think of a single case where setting that would be anything but wrong.

**Comment by youngm** [comment]
We could.  Though I actually set that for an application, as a stop gap, that was having trouble staying within the container memory size while I study the problem.  We set it to a value that we believed should leave plenty of head room for everything else.  It was convenient.

That said I won't have a problem with making it an undocumented feature if you would prefer.

**Comment by nebhale** [comment]
Yeah, let's make it undocumented.  I understand your use case, but I don't want any indication in our docs that it's an appropriate thing for most users to do.  Those who really need it should be able to divine that it's possible for the pattern of the rest.

**Comment by youngm** [comment]
@nebhale done.

**Pull request closed without merging**
